core/urls.py
# finegap/urls.py

from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    
    path('accounts/login/', auth_views.LoginView.as_view(template_name='core/login.html'),name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('login/signup/',views.signup, name="signup"),
   
    path('contacto/', views.contacto, name='contacto'),
    path('contacto/mensajes_listado', views.mensajes_listado, name="mensajes_listado"),

    path('acerca_de/', views.acerca_de, name='acerca_de'),

    path('administracion/', views.administracion, name='administracion'),

    path('mostrar_destinos/', views.mostrar_destinos, name='mostrar_destinos'),
    path('alta_destinos', views.DestinosCreateView.as_view(), name="alta_destinos"),
    path('mostrar_destinos/modificar_destino/<int:pk>', views.modificar_destino, name='modificar_destino'),
    path('mostrar_destinos/eliminar_destino/<int:pk>', views.eliminar_destino, name='eliminar_destino'),

    path('mostrar_excursiones/', views.mostrar_excursiones, name='mostrar_excursiones'),
    path('alta_excursion', views.ExcursionesCreateView.as_view(), name="alta_excursion"),
    path('mostrar_excursiones/modificar_excursion/<int:pk>', views.modificar_excursion, name='modificar_excursion'),
    path('mostrar_excursiones/eliminar_excursion/<int:pk>', views.eliminar_excursion, name='eliminar_excursion'),
   
    path('travels/', views.travel_list, name='travel_list'),
    path('travel/<int:pk>/', views.travel_detail, name='travel_detail'),
    path('travel/travel_detail_admin/<int:pk>/', views.travel_detail_admin, name='travel_detail_admin'),
    path('travel/travel_new/', views.travel_new, name='travel_new'),
    path('travel/travel_edit/<int:pk>', views.travel_edit, name='travel_edit'),
    path('travel/<int:pk>/delete/', views.travel_delete, name='travel_delete'),

    path('error/', views.error_404, name='error'),

]

turismo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf  import settings
from django.conf.urls.static  import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('turismo/', include('core.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.core.exceptions import ValidationError
from .choices import tipos
from django.urls import reverse
from django.contrib.auth.models import User


# Create your models here.

#------------------------------------------------------------------
# tabla que contiene los destinos que se pueden contratar
#------------------------------------------------------------------

class Destinos(models.Model):
    # Campos
    Id = models.CharField(max_length=20, verbose_name='ID de Destino')
    city = models.CharField(
        max_length=20,
        verbose_name='Ciudad',
        )
    country = models.CharField(
        max_length=100, 
        verbose_name='Pais',
        )
    description = models.CharField(
        max_length=1000, 
        verbose_name='Descripcion',
        )
    urlImg = models.ImageField(
        upload_to='locations-img', 
        null=True, 
        verbose_name='Destinos',
        )
    tipo = models.CharField(
        max_length=1, 
        default=1,
        choices=tipos,
        verbose_name='Estado',
        )

    # Metadata
    class Meta:
        ordering = ["city"]

    # Metodos
    def detalle_destinos(self):
        return f"{self.city} -- {self.country}"
    
    def __str__(self):
        return self.detalle_destinos()


    def clean_Id(self):
        return self.cleaned_data['Id']
    
    def clean_city(self):
        return self.cleaned_data['city']
    
    def clean_country(self):
        return self.cleaned_data['country']


#------------------------------------------------------------------
# tabla que contiene las excursiones que se pueden contratar
#------------------------------------------------------------------

class Excursiones(models.Model):
    # Campos
    city = models.CharField(
        max_length=20,
        verbose_name='Ciudad',
        )
    description = models.CharField(
        max_length=1000, 
        verbose_name='Descripcion',
        )
    valor = models.FloatField(
        default=0,
        verbose_name='valor',
        )
    tipo = models.CharField(
        max_length=1, 
        default=1,
        # choices=estado,
        verbose_name='Estado',
        )

    # Metadata
    class Meta:
        ordering = ["city"]

    # Metodos
    def detalle_excursiones(self):
        return f"{self.city} -- {self.description}"
    
    def __str__(self):
        return self.detalle_excursiones()
  
    def clean_city(self):
        return self.cleaned_data['city']
    

#------------------------------------------------------------------
# Tabla Travel para registrar cada viaje contratado por un usuario
#------------------------------------------------------------------

class Travel(models.Model):
    # Campos
    destino = models.ForeignKey(
        Destinos, 
        on_delete=models.CASCADE,
        null=True,
        blank=True, 
        verbose_name='Destino',
        )
    fecha_desde = models.DateField(
        null=True,
        verbose_name='Fecha Desde',
        )
    fecha_hasta = models.DateField(
        null=True,
        verbose_name='Fecha hasta',
        )
    valor = models.FloatField(
        default=0,
        verbose_name='valor',
        )
    pasajeros = models.SmallIntegerField(
        default=1,
        verbose_name='pasajeros',
        )
    usuarios = models.ForeignKey(
        User, 
        on_delete=models.CASCADE,
        null=True,
        blank=True, 
        verbose_name='Usuario',
        )
    excursiones = models.ManyToManyField(
        Excursiones, 
        through="Excursiontravel",
        blank=True, 
        verbose_name='Excursion',
        )


    # Metodos
    def travel_destinos(self):
        return f"{self.excursiones} -- {self.destino}"
    
    def __str__(self):
        return self.travel_destinos()
    
#------------------------------------------------------------------
# Tabla intermedia para trabajar con relaciones many to many (Travel - Usuarios)
#------------------------------------------------------------------

class Excursiontravel(models.Model):
    # Campos
    travel = models.ForeignKey(
        Travel,
        on_delete=models.CASCADE,
         null=True,
         blank=True, 
        verbose_name="Travel",
    )
    excursiones = models.ForeignKey(
        Excursiones,
        on_delete=models.CASCADE,
         null=True,
         blank=True, 
        verbose_name="Excursiones",
    )

        # Metodos
    def travel_excursiones(self):
        return f"{self.travel} -- {self.excursiones}"
    
    def __str__(self):
        return self.travel_excursiones()
    
#------------------------------------------------------------------
# Tabla para registrar mensajes de usuarios
#------------------------------------------------------------------

class Contacto(models.Model):
    # Campos
    name = models.CharField(
        max_length=20,
        verbose_name='nombre',
        )
    lastname = models.CharField(
        max_length=20,
        verbose_name='Apellido',
        )
    email = models.CharField(
        max_length=200,
        verbose_name='Email',
        )
    subject = models.CharField(
        max_length=200,
        verbose_name='Asunto',
        )
    message = models.CharField(
        max_length=500,
         verbose_name='Mensaje',
        )
    fecha = models.DateField(
        null=True,
        verbose_name='Fecha',
        )
    
    # Metadata
    class Meta:
        ordering = ["fecha"]

    # Metodos
    def detalle_FormContacto(self):
        return f"{self.name}"
    
    def __str__(self):
        return self.detalle_FormContacto()


#------------------------------------------------------------------
# Tabla intermedia para trabajar con relaciones many to many (Travel - Usuarios)
#------------------------------------------------------------------

# class Usertravel(models.Model):
#     # Campos
#     travel = models.ForeignKey(
#         Travel,
#         on_delete=models.CASCADE,
#          null=True,
#          blank=True, 
#         verbose_name="Travel",
#     )
#     usuarios = models.ForeignKey(
#         User,
#         on_delete=models.CASCADE,
#          null=True,
#          blank=True, 
#         verbose_name="Usuario",
#     )
#     fecha = models.DateField(
#         null=True,
#         verbose_name='Fecha',
#         )


    


core/forms.py
# forms.py

from django import forms
from .models import Destinos, Excursiontravel, Excursiones, Travel
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


# formulario para dar de alta un usuario

class SignupForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ('username', 'email', 'password')

# formulario para dar de alta un destino

class AltaDestinos(forms.ModelForm):
    class Meta:
        model = Destinos
        fields = '__all__'


class TravelForm(forms.ModelForm):
    class Meta:
        model = Travel
        fields = ['destino', 'fecha_desde', 'fecha_hasta', 'valor', 'pasajeros', 'usuarios', 'excursiones']
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # Excluye usuario admin
        self.fields['destino'].queryset = Destinos.objects.exclude(tipo=3)
    
        # Excluye usuario admin
        self.fields['usuarios'].queryset = User.objects.exclude(id=1)

class DestinosForm(forms.ModelForm):
    class Meta:
        model = Destinos
        fields = ['Id', 'city', 'country', 'description', 'urlImg', 'tipo']

class ExcursionesForm(forms.ModelForm):
    class Meta:
        model = Excursiones
        fields = ['city', 'description', 'valor', 'tipo']

class ExcursiontravelForm(forms.ModelForm):
    class Meta:
        model = Excursiontravel
        fields = ['travel', 'excursiones']

core/templates/core/acerca_de.html
{% extends "core/layout.html" %}
{% load static %}
{% block extra_css%}
  <link rel="stylesheet" href="{% static 'core/css/style_pages.css' %}">
  <link rel="stylesheet" href="{% static 'core/css/style_aboutus.css' %}">
  {%endblock%}

{% block title %}Nosotros{% endblock %}
{% block content %}

    <div class="Main">
      <h2 class="title-section">NOSOTROS INTEGRAMOS EL EQUIPO DE MOCHILEANDO</h2>
      <div class="articles">
        <article>
          <div class="article-wrapper img-team">
            <img id="img-team" src="{% static 'core/images/team.png' %}" style="border-radius: 16px" alt="Team">
            <div class="article-body">
              <h2>¿Buscas un lugar especial para tus vacaciones?</h2>
              <p>
                mochileando.com no es el sitio promedio de reserva para tus vacaciones,
                aqui encontrarás todo lo que estas buscando y mas,
                lugares increibles para conocer y tickets para excurciones fantasticas.
                <br><br>
                Tenemos la crème de la crème de los hostels y recorridos guiados en toda
                Latinoamerica con tickets listos para comprar ahora mismo.
                <br><br>

                También somos más prácticos que los sitios promedio. Desglosamos toda la información
                que necesita saber en pequeños fragmentos y te brindamos consejos y trucos
                de expertos para que puedas reservar feliz, sin dolores de cabeza.
              </p>
              <br>
              <br>
            </div>
          </div>
        </article>
      </div>
    </div>
  <script src="{% static 'core/js/index.js' %}"></script>

    {% endblock %}

core/templates/core/administracion.html
{% extends "core/layout.html" %}
{% load static %}
{% block extra_css%}
<link rel="stylesheet" href="{% static 'core/css/style_pages.css' %}">
<link rel="stylesheet" href="{% static 'core/css/estilo.css' %}">
{%endblock%}

{% block title %}administracion{% endblock %}
{% block content %}

<div class="Main">
    <div id="central">
        <div id="login">
            <div class="div-logo">
                <script src="https://cdn.lordicon.com/ritcuqlt.js"></script>
                <lord-icon id="logo" src="https://cdn.lordicon.com/vkweisbr.json" trigger="loop-on-hover" delay="2000"
                    colors="outline:#121331,primary:#646e78,secondary:#2ca58d,tertiary:#1d4e89"
                    style="width:100px;height:100px"> </lord-icon>
                <h2 class="welcome">Seleccione opcion</h2>
                <div class="pie-form">
                    <a href="{% url 'mostrar_destinos' %}">Administrar Destinos</a>
                    <br>
                    <a href="{% url 'mostrar_excursiones' %}">Administrar Excursiones</a>
                    <br>
                    <a href="{% url 'travel_list' %}">Paquetes vendidos</a>
                </div>
            </div>
        </div>
    </div>
</div>
</div>

<script src="{% static 'core/js/index.js' %}"></script>

{% endblock %}

<!-- <form method="post" action="{% url 'login' %}">
    {% csrf_token %}
    <table>
        <tr>
            <td>Nombre Usuario :</td>
            <td class="form-control">{{ form.username }}</td>
        </tr>
        <tr>
            <td>Contraseña</td>
            <td class="form-control">{{ form.password }}</td>
        </tr>
    </table>

    <input type="submit" value="login">
    <input type="hidden" name="next" value="{{ next }}">
</form> -->

core/templates/core/alta_destinos.html
{% extends "core/layout.html" %}
{% load static %}
{% block extra_css%}
<link rel="stylesheet" href="{% static 'core/css/style_pages.css' %}">
<link rel="stylesheet" href="{% static 'core/css/administracion.css' %}">
{%endblock%}

{% block title %}Alta de Destinos{% endblock %}
{% block section_title %}Alta de Destinos{% endblock %}
{% block content %}
<div class="Main">

    <a id="alta"></a>
    <div id="alta">
        <div class="itemTitulo" style="margin-left: 5%">
            <h1>Alta Destino </h1>
        </div>

        <div class="form_alta_destino">

            <h3 style="text-align:center">Datos del nuevo destino</h3>
            <form method="post" enctype="multipart/form-data" action="{% url 'alta_destinos' %}">
                {% csrf_token %}
                <!-- {{ form.as_p }} -->
                <table style="width:50%" align="center">
                    <tr>
                        <td>Destino</td>
                        <td><input type="text" class="estilo_input" name="Id" autofocus></td>
                    </tr>
                    <tr>
                        <td>Ciudad</td>
                        <td><input type="text" class="estilo_input" name="city"></td>
                    </tr>
                    <tr>
                        <td>Pais</td>
                        <td><input type="text" class="estilo_input" name="country"></td>
                    </tr>
                    <tr>
                        <td>Descripcion</td>
                        <td><input type="textarea" class="estilo_input" name="description"></td>
                    </tr>
                     <tr>
                        <td>Imagen</td>
                        <td>
                            <input type="file" name="urlImg">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <label for="tipo">Seleccione Estado</label>
                        </td>
                        <td>
                            <select id="tipo" name="tipo" onChange="">
                                <option  value="1" selected="selected">Elegidos</option>
                                <option  value="2" >Recomendados</option>
                                <option  value="3" >inactivo</option>
                            </select>                        
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2" align="center">
                            <input type="submit" value="Confirmar" class="btn btn-success">
                            <p>
                                <a class="volver" href="{% url 'mostrar_destinos' %}">         Volver</a>
                            </p>
                        </td>
                    </tr>
                </table>
        
            
            </form>
        </div>
    </div>

</div>
<script src="{% static 'core/js/index.js' %}"></script>
{% endblock %}

core/templates/core/alta_excursion.html
{% extends "core/layout.html" %}
{% load static %}
{% block extra_css%}
<link rel="stylesheet" href="{% static 'core/css/style_pages.css' %}">
<link rel="stylesheet" href="{% static 'core/css/administracion.css' %}">
{%endblock%}

{% block title %}Alta de Excursion{% endblock %}
{% block section_title %}Alta de Excursion{% endblock %}
{% block content %}
<div class="Main">

    <a id="alta"></a>
    <div id="alta">
        <div class="itemTitulo" style="margin-left: 5%">
            <h1>Alta Excursion </h1>
        </div>

        <div class="form_alta_destino">

            <h3 style="text-align:center">Datos de la Excursion</h3>
            <form method="post" action="{% url 'alta_excursion' %}">
                {% csrf_token %}
                <table style="width:50%" align="center">
                    <tr>
                        <td>Ciudad</td>
                        <td><input type="text" class="estilo_input" name="city"></td>
                    </tr>
                    <tr>
                        <td>Descripcion</td>
                        <td><input type="textarea" class="estilo_input" name="description"></td>
                    </tr>
                     <tr>
                        <td>Valor</td>
                        <td><input type="text" class="estilo_input" name="valor"></td>
                    </tr>
                    <tr>
                        <td>
                            <label for="tipo">Seleccione Estado</label>
                        </td>
                        <td>
                            <select id="tipo" name="tipo" onChange="">
                                <option  value="1" selected="selected">Activo</option>
                                <option  value="2" >inactivo</option>
                            </select>                        
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2" align="center">
                            <input type="submit" value="Confirmar" class="btn btn-success">
                            <p>
                                <a class="volver" href="{% url 'mostrar_excursiones' %}">         Volver</a>
                            </p>
                        </td>
                    </tr>
                </table>
        
            
            </form>
        </div>
    </div>

</div>
<script src="{% static 'core/js/index.js' %}"></script>
{% endblock %}

core/templates/core/alta_travel.html
{% extends "core/layout.html" %}
{% load static %}
{% block extra_css%}
<link rel="stylesheet" href="{% static 'core/css/administracion.css' %}">
{%endblock%}
{% block title %}Alta Travel{% endblock %}
{% block content %}
<div class="Main">

    <h2 style="text-align:center"> Destinos Seleccionado</h2>
    <form  method="POST" enctype="multipart/form-data" action="">
        {% csrf_token %}
        <!-- {{ form.as_p }} -->
        <table style="width:50%" align="center">
            <tr>
                <td>Destino</td>
                <td><input type="text" value="{{ destinos.Id }}" name="Id" readonly></td>
            </tr>
            <tr>
                <td>Ciudad</td>
                <td><input type="text" value="{{ destinos.city }}" name="city" readonly></td>
            </tr>
            <tr>
                <td>Pais</td>
                <td><input type="text" value="{{ destinos.country }}" name="country" readonly></td>
            </tr>
            <tr>
                <td>Descripcion</td>
                <td><input type="text" value="{{ destinos.description }}" name="description" readonly></td>
            </tr>
            <tr>
                <td>Imagen</td>
                <td>
                    {% if destinos.urlImg %}
                    <img src="{{destinos.urlImg.url}}" style="height:50px; width:50px;" alt="...">
                    <!-- <input type="file" name="urlImg"> -->
                    {% else %}
                    <img src="" style="height:50px; width:50px;" alt="...">
                    {% endif %}
                </td>
            </tr>
            <tr>
                <td>Fecha Desde</td>
                <td><input type="date" min="2023-11-11" max="2024-03-31"
                    step="7" class="estilo_input" name="fecha_desde" autofocus></td>
            </tr>
            <tr>
                <td>Fecha hasta</td>
                <td><input type="date" min="2023-11-11" max="2024-03-31"
                    step="7" class="estilo_input" name="fecha_hasta" autofocus></td>
            </tr>
            <tr>
                <td>Costo total</td>
                <td><input type="text" class="estilo_input" name="valor" autofocus></td>
            </tr>
            <tr>
                <td>Pasajeros</td>
                <td><input type="text" class="estilo_input" name="pasajeros" autofocus></td>
            </tr>

            <tr>
                <td colspan="2" align="center">
                    <input type="submit" value="Confirmar" class="btn btn-success">
                    <br>
                    <p>
                        <a class="volver" href="{% url 'mostrar_destinos' %}">Volver</a>
                    </p>
                </td>
            </tr>
        </table>
    </form>
</div>
<script src="{% static 'core/js/index.js' %}"></script>
{% endblock %}

<!-- <tr>
    <td>
        <label for="tipo">Seleccione Estado</label>
    </td>
    <td>
        <select id="tipo" name="tipo" onChange="">
            <option  value="1" >Elegidos</option>
            <option  value="2" >Recomendados</option>
            <option  value="3" >inactivo</option>
        </select>                        
    </td>
</tr> -->

core/templates/core/contacto.html
{% extends "core/layout.html" %}
{% load static %}
{% block extra_css%}
<link rel="stylesheet" href="{% static 'core/css/style_contacto.css' %}">
{%endblock%}

{% block title %}Contacto{% endblock %}
{% block content %}
<div class="Main">
  <div class="itemTitulo">
    <h1>Cont&aacutectenos</h1>
  </div>
  <div class="itemMapa">
    <iframe
      src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d26266.27064110574!2d-58.43425612005323!3d-34.62226705189999!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x95bccb0de996fa65%3A0x47296bd9e98ee2ad!2sUspallata%203150%2C%20C1437JCJ%20CABA!5e0!3m2!1ses!2sar!4v1695075658807!5m2!1ses!2sar"
      width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"
      referrerpolicy="no-referrer-when-downgrade"></iframe>
  </div>
  <form method="POST" action="{% url 'contacto' %}">
    {% csrf_token %}

    <table style="width:50%" align="center">
      <tr>
        <td>Usuario</td>
        <td><input type="text" value="{{ user.id }}" name="Id" readonly></td>
      </tr>
      <tr>
        <td>Nombre</td>
        <td><input type="text" value="{{ user.username }}" name="name" readonly></td>
      </tr>
      <tr>
        <td>Apellido</td>
        <td><input type="text" value="{{ user.last_name }}" name="lastname" readonly></td>
      </tr>
      <tr>
        <td>Correo</td>
        <td><input type="text" value="{{ user.email }}" name="email" readonly></td>
      </tr>
      <tr>
        <td>Asunto</td>
        <td><input type="text" name="subject" autofocus></td>
      </tr>
      <tr>
        <td>Mensaje</td>
        <td><input type="text" name="message"></td>
      </tr>
    </table>

    <button class="btn" type="submit">Enviar formulario</button>
    {% if perms.core.view_contacto %}
    <a href="{% url 'mensajes_listado' %}">Ver mensajes</a>
    {% endif %}
  </form>
</div>
<script src="{% static 'core/js/index.js' %}"></script>

{% endblock %}

core/templates/core/eliminar_excursion.html
{% extends "core/layout.html" %}
{% load static %}
{% block extra_css%}
<link rel="stylesheet" href="{% static 'core/css/administracion.css' %}">
{%endblock%}
{% block title %}Alta de Excursion{% endblock %}
{% block content %}
<div class="Main">

    <form method="POST" action="">
        {% csrf_token %}

        <br><br>
        <div class="alert alert-danger" role="alert">
            Esta seguro que quiere eliminar esta Excursion?
             Ciudad ==> {{ excursion.city}} Descripcion ==> {{ excursion.description}}
        </div>
        <br><br>

        <div class="alert alert-danger" role="alert">
            <a href="{% url 'mostrar_excursiones' %}"><-- Volver</a>
            <p>
                <input class="btn btn-danger" type="submit" value="Confirmar">
            </p>
        </div>
    </form>
</div>
<script src="{% static 'core/js/index.js' %}"></script>
{% endblock %}

core/templates/core/error_404.html
{% extends "core/layout.html" %}
{% load static %}
{% block extra_css%}
    <link rel="stylesheet" href="{% static 'core/css/style_pages.css' %}">
{%endblock%}
{% block title %}Error{% endblock %}
{% block content %}
<div class="Main">
    <div class="container-error item-center">
        <lord-icon src="https://cdn.lordicon.com/vyukcgvf.json" trigger="loop-on-hover" delay="1000"
            class="item-center icon-error" colors="outline:#121331,primary:#ffc738,secondary:#92140c" stroke="60">
        </lord-icon>
        <h1 class="item-center">Error 404</h1>
        <h3 class="item-center">Página en construcción</h3>
    </div>
</div>
<script src="{% static 'core/js/index.js' %}"></script>

 {% endblock %}

core/templates/core/excursiontravel.html
{% extends "core/layout.html" %}
{% load static %}
{% block extra_css%}
<link rel="stylesheet" href="{% static 'core/css/administracion.css' %}">
{%endblock%}
{% block title %}Alta Travel{% endblock %}
{% block content %}
<div class="Main">

    <h2 style="text-align:center"> Destinos Seleccionado</h2>
    <form  method="POST" action="">
        {% csrf_token %}
        {{ travelform_form.as_p }}
        {{ excursiontravel_form.as_p }}
        <input type="submit" value="Guardar">
   </form>
</div>
<script src="{% static 'core/js/index.js' %}"></script>
{% endblock %}

<!-- <tr>
    <td>
        <label for="tipo">Seleccione Estado</label>
    </td>
    <td>
        <select id="tipo" name="tipo" onChange="">
            <option  value="1" >Elegidos</option>
            <option  value="2" >Recomendados</option>
            <option  value="3" >inactivo</option>
        </select>                        
    </td>
</tr> -->

core/templates/core/login.html
{% extends "core/layout.html" %}
{% load static %}
{% block extra_css%}
<link rel="stylesheet" href="{% static 'core/css/style_pages.css' %}">
<link rel="stylesheet" href="{% static 'core/css/estilo.css' %}">
{%endblock%}

{% block title %}Login{% endblock %}
{% block content %}

<div class="Main">
    <div id="central">
        <div id="login">
            <div class="div-logo">
                <script src="https://cdn.lordicon.com/ritcuqlt.js"></script>
                <lord-icon id="logo" src="https://cdn.lordicon.com/vkweisbr.json" trigger="loop-on-hover" delay="2000"
                    colors="outline:#121331,primary:#646e78,secondary:#2ca58d,tertiary:#1d4e89"
                    style="width:100px;height:100px"> </lord-icon>
                <h2 class="welcome">BIENVENIDOS</h2>
            </div>
            <form method="post" action="{% url 'login' %}">
                {% csrf_token %}
                <table>
                    <tr>
                        <td>Nombre Usuario :</td>
                        <td class="form-control">{{ form.username }}</td>
                    </tr>
                    <tr>
                        <td>Contraseña</td>
                        <td class="form-control">{{ form.password }}</td>
                    </tr>
                </table>

                <input type="submit" value="login">
                <input type="hidden" name="next" value="{{ next }}">
            </form>
            <div class="pie-form">
                <a href="{% url 'error' %}">¿Olvidaste tu contraseña?</a>
                <a href="{% url 'signup' %}">¿No tienes Cuenta? Registrate</a>
                <a href="{% url 'home' %}">← Volver</a>
            </div>
        </div>
    </div>
</div>
</div>

<script src="{% static 'core/js/index.js' %}"></script>

{% endblock %}

core/templates/core/mensajes_listado.html
{% extends "core/layout.html" %}
{% load static %}
{% block extra_css%}
<link rel="stylesheet" href="{% static 'core/css/administracion.css' %}">
{%endblock%}

{% block title %}Listado Mensajes{% endblock %}
{% block section_title %}Listado De Mensajes{% endblock %}
{% block content %}
<div class="Main">
    <div class="form_mensajes"><h2 style="text-align:center"> Contactos recibidos </h2>
        <table align="center" style="margin: 20px 40px;">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Apellido</th>
                    <th>Email</th>
                    <th>Asunto</th>
                    <th>Mensaje</th>
                </tr>
            </thead>
            <tbody>
                {% for mensaje in mensajes %}
                <tr>
                    <td>{{mensaje.name}}</td>
                    <td>{{mensaje.lastname}}</td>
                    <td>{{mensaje.email}}</td>
                    <td>{{mensaje.subject}}</td>
                    <td>{{mensaje.message}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

    </div>
</div>
{% endblock %}

core/templates/core/signup.html
{% extends 'core/layout.html'%}
{% load static %}
{% block extra_css%}
<link rel="stylesheet" href="{% static 'core/css/style_pages.css' %}">
<link rel="stylesheet" href="{% static 'core/css/estilo.css' %}">
{%endblock%}

{% block title %}Registrarse{% endblock %}

{%block content %}

<h1>Registrarse</h1>
<form action="{% url 'signup' %}" method='POST'>
    {% csrf_token %}

    {{ form.as_p }}
    <button class="btn" type="submit">Registrarse</button>

</form>
<br>
<br>
<br>
<script src="{% static 'core/js/index.js' %}"></script>

{% endblock %}